### ISSUE TITLE
Decide how data should be served from BE to FE for an applicant

### ISSUE THREAD

**Issue by ErinUntermeyer** [HireUp-Turing/HireUp_frontend#11]
- Add this to the BE README

FIRST DRAFT:
ENDPOINT: `GET /api/v1/applicant/:id`

```
{
  "data": {
​    "id": "1",
​    "applicant": {
​      "username": "random name",
​      "email": "email@email.com",
​      "created_at": "timestamp",
​      "updated_at": "timestamp"
​    },
​    "messages": {
​      "applicant_id": "1",
​      "employer_name": "google",
​      "employer-email": "google@email.com",
​      "body": "message goes here",
​      "read_status": "boolean"
​    },
​    "skills": ["javascript", "react"],
​    "values": ["paired programming", "teamwork"]
  }
}
```

**Comment by GreysonElkins** [comment]
I agree that we shouldn't serve user information (first/last name) in API responses. I don't know that we need the email either. I can understand why those would be stored though.

Messages should probably be an array of objects that look like the one here. 

I believe BE was planning on using ENUMs for `messages.read_status` (corresponding to values `unread`, `ignored`, and `responded`

`Messages` may need their own id as well, which BE has accounted for. I'm not sure if it'd be necessary or usable on the front end side, but 'created_at' would be nice for sure.

Why is the applicants `id` in a separate object? If this is the response to a request for a user, those may be better on the first level of the object.

`applicant.updated_at` could be nice to have so we can "favor" more recently active users - but it and `applicant.created_at` aren't super necessary.

**Comment by amykarnaze** [comment]
Depending on how we get messaging complete. Should we consider an email for applicant/employer connection?

Should messages be an array? Is this for easy iterating? Message id makes sense.

+1 vote for Enums and user id.

I like the idea of displaying applicant results based on more recent users.

**Comment by ErinUntermeyer** [comment]
Thank you for the input y'all, these are all great ideas.
- For just the GET request for an applicant, I do agree that we probably should not get back the email as we don't want/need that information displayed anywhere.
- Messages are definitely better as an array for easy iterating, I'll reformat that.
- I am down for the ENUM train, although the concept feels a little fuzzy to me... **let me know if I properly accounted for that in the updated response object below.**
- Also +1 for displaying applicant results based on the more recent users but curious how this will come into play when we also account for skills and values. If the user has 3 matched skills but another user has 2 matched skills AND a more recent updated profile, which one displays first? We would have to incorporate both in the returned results. Something to think about when we get closer to writing that logic.

SECOND DRAFT:
ENDPOINT: GET /api/v1/applicant/:id

```
{
  "data": {
​    "id": "1",
​    "username": "random name",
​    "updated_at": "timestamp",
​    "messages": [
      {
​      "applicant_id": "1",
      "message_id": "1",
​      "employer_name": "google",
​      "employer_email": "google@email.com",
​      "body": "message goes here",
​      "read_status": "unread" OR "ignored" OR "responded"
​       },
       {
​      "applicant_id": "1",
      "message_id": "2",
​      "employer_name": "Aerion Inc",
​      "employer_email": "aerioninc@email.com",
​      "body": "message goes here",
​      "read_status": "unread" OR "ignored" OR "responded"
​       }
     ],
​    "skills": ["javascript", "react"],
​    "values": ["paired programming", "teamwork"]
  }
}
```

Let me know if there are any changes we need to make to this draft!

**Comment by GreysonElkins** [comment]
##### note from @gabichuelas: 

GET applicant endpoint

`GET /api/v1/applicants/:id`
`GET /api/v1/applicants`

(FE has it written down as /api/v1/applicant/:id, I think applicant needs to stay plural to follow all our other examples of restful paths)

**Comment by ErinUntermeyer** [comment]
This would be called when the "Search" button is clicked and we get back all matched applicants. Based on a conversation with BE team, we agreed that for this request we do not need the messages. Those should instead be returned when we get back a single applicant.

`GET /api/v1/applicants/:id`

```
{
  "data": {
​    "id": "1",
​    "username": "random name",
​    "updated_at": "timestamp",
​    "skills": ["javascript", "react"],
​    "values": ["paired programming", "teamwork"]
  }
}
```

**Comment by gabichuelas** [comment]
Need to decide if we need something like 'username'.
Right now the `Applicants` table has an `id`, `email`, `first_name`, `last_name`, timestamps.
