### ISSUE TITLE
Search Request Object

### ISSUE THREAD

**Issue by GreysonElkins** [HireUp-Turing/HireUp_frontend#31]
As of right now when we send a `fetch` for search we'll be including an object that looks like this. 
```
{
  query: {
    skills: [{attribute:"Java", checked:true}, {attribute:"Magic", checked:true}],
    values: [{attribute:"heartfelt talks", checked:true}, {attribute:"bring your turtle to work day", checked:true}] 
  }
}
```
The checked property for these objects is data that is used for rendering on the FE, but by the time it reaches BE the arrays will only contain attributes which are `checked`. 

Is this going to cause trouble for y'all? Should we clean this data before sending it? Is the `{query:{...}}` format going to work for y'all?

**Comment by rrabinovitch** [comment]
acknowledging that I saw this but haven't been able to consider the question yet - will get back to you with an answer later today!

**Comment by GreysonElkins** [comment]
@rrabinovitch and @gabichuelas, following our conversation, I'm under the impression that our search request will contain an object like this, can y'all confirm?
```
{
  skills: [1, 2, 3]
  values: [4, 5, 6]
}
```

**Comment by rrabinovitch** [comment]
@GreysonElkins yessir
