### ISSUE TITLE
Update Lorem Ipsum

### ISSUE THREAD

**Issue by GreysonElkins** [HireUp-Turing/HireUp_frontend#60]

**Comment by rrabinovitch** [comment]
Feel free to edit:

HireUp aims to minimize bias in the hiring process, and reduce efforts required of job applicants to produce application materials and of employers to read through piles of those materials.

As a job seeker, you can you create an anonymous applicant profile that highlights your skills and values. When an employer comes across your profile and believes you'd be a good fit for their open role, they'll message you to indicate their interest in connecting further.

As an employer looking to hire, you can browse anonymous applicant profiles, filtering for applicants that have the skills and values needed for your open roles. When you find an applicant profile that looks like a good fit for an open role, send the applicant a message and invite them to interview with your company.

**Comment by rrabinovitch** [comment]
If you could include a screenshot/gif of the updated homepage and tag me when it's ready, that'd be sweet - I've currently got a gif with the lorem ipsum text [here](https://github.com/HireUp-Turing/HireUp_backend/tree/documentation_updates#hireup---backend-api-in-flask) in the back-end readme and would love to get that updated when this is ready
